version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build
      - save_hello_world_output:
          requires:
            - "build"
      - retrieve_output:
          requires:
            - "save_hello_world_output"


jobs:
  build:
    working_directory: ~/mern-starter
    docker:
      - image: circleci/node:10.16.3
      - image: mongo:4.2.0
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@5'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
      - run:
          name: code-coverage
          command: './node_modules/.bin/nyc report --reporter=text-lcov'
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-results.xml
  save_hello_world_output:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run: mkdir -p /tmp/workspace
      - run:
          name: "write to file"
          command: 'echo "hello world" > /tmp/workspace/output.txt'
      - persist_to_workspace:
         root: /tmp/workspace
         paths:
           - "/output.txt"
  retrieve_output:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: cat_output
          command: 'cat ./output.txt'


