version: 2.1

commands:
  sayhello:
    description: "A very simple command for demonstration purposes"
    parameters:
      to:
        type: string
        default: "Hello World"

    steps:
      - run: echo << parameters.to >>
  print_pipeline_id:
    description: "Command is used to print pipeline id"
    parameters:
      pipeline_id:
        type: string
        default: $CIRCLE_WORKFLOW_ID
    steps:
      - run: echo << parameters.pipeline_id >>

workflows:
  version: 2
  build:
    jobs:
      - build
      - save_hello_world_output:
          requires:
            - "build"
      - retrieve_output:
          requires:
            - "save_hello_world_output"
      - using_command:
          requires:
            - "retrieve_output"
      - handle_a_job_failure:
          requires:
            - "using_command"


jobs:
  build:
    working_directory: ~/mern-starter
    docker:
      - image: circleci/node:10.16.3
      - image: mongo:4.2.0
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@5'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
      - run:
          name: code-coverage
          command: './node_modules/.bin/nyc report --reporter=text-lcov'
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-results.xml
  save_hello_world_output:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: "write to file"
          command: 'echo "hello world" > ~/output.txt'
      - persist_to_workspace:
         root: ~/
         paths:
           - output.txt
  retrieve_output:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run:
          name: cat_output
          command: 'cat ~/output.txt'
  using_command:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - sayhello:
          to: "Duy Pham"
  handle_a_job_failure:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - run:
          name: return_failure
          command: 'return 1'
      - run:
          name: Failure notification
          command: 'echo "Failure"'
          when: on_fail

